### PR TITLE
Feature/auto load vocabularies by profile

### LINKED ISSUE #61: Add support for USGS Thesaurus?
See: https://www2.usgs.gov/science/about/

### LINKED ISSUE #459: Allow profile to specify vocabularies to be included in metadata records
The mdProfile descriptions (in json) need to be extended to include information about vocabularies that are included in the profile. 

This extension must include:
1. information that a user needs to select the profile and attach it to a record
2. information that mdEditor needs to facilitate inclusion of the vocabulary in a metadata record: (vocabulary properties, terms, and definitions).

For example, in the case of [vocabularies from scienceBase](https://www.sciencebase.gov/vocab/), the sciencebase id for the vocabulary provides access to the vocabulary home page and to items in the vocabulary. For example, the Datacite Contributor Type vocabulary has the id [6123b2c3bac0c745ec5f2199](https://www.sciencebase.gov/vocab/vocabulary/6123b2c3bac0c745ec5f2199)  

Related issues: [#450](https://github.com/adiwg/mdEditor/issues/450)

### LINKED ISSUE #460: Update vocabularies in a profile
mdEditor currently includes the capability to update profile definitions from git repositories or other sources. This process should include the capability to update vocabularies included in the profile from appropriate sources at the same time.
Related issues: [#450](https://github.com/adiwg/mdEditor/issues/450)

### LINKED ISSUE #482: Allow user to add ScienceBase vocabulary
# Summary
Allow user to add an existing ScienceBase vocabulary by providing an endpoint to a vocabulary list.

The initial implementation should allow a user to provide an endpoint for a USGS ScienceBase vocabulary term list (https://www.sciencebase.gov/vocab/). Future implementation may be extended to support other custom vocabularies or hierarchical thesauri.

# Features
  - Allow user to provide endpoint to a vocabulary (e.g. "LCC Project Categories"; https://www.sciencebase.gov/vocab/vocabulary/52dee7c5e4b0dee2a6cd6b18).
     - https://www.sciencebase.gov/vocab/vocabulary/52dee7c5e4b0dee2a6cd6b18?format=json
  - Validate the endpoint ("nodeType" = "vocabulary")
  - Validate that vocabulary contains contains at least one term ("nodeType" = "term")
    - True example: https://www.sciencebase.gov/vocab/vocabulary/52dee7c5e4b0dee2a6cd6b18/terms?format=json
    - False example: https://www.sciencebase.gov/vocab/vocabulary/58d4255ee4b0f974afcf03cb/terms?format=json
  - Generate term list from the "name" attribute for presentation to user when "Edit Keywords" is selected. (https://www.sciencebase.gov/vocab/vocabulary/52dee7c5e4b0dee2a6cd6b18/terms?format=json)
  - Display "description", if present,  as mouse-over text
  - Subsequent access would present complete term list, allowing for additional term selections by user.

# Example
  - In addition to "Add Thesaurus" there would be a "Add from ScienceBase" (or similar)
    - Or "Pick a thesaurus" list could have option to "add from ScienceBase", "Add Endpoint" or similar
  - User would be presented with dialog to enter ScienceBase thesaurus endpoint.
    - Example. A current vocabulary is "LCC Project Category" which has an endpoint of: https://www.sciencebase.gov/vocab/vocabulary/52dee7c5e4b0dee2a6cd6b18
    - Thesaurus information: Endpoint = URL; what about other fields?
  - On success
    - User selects "Edit Keywords" and terms are displayed for selection.

# Notes
  - Some vocabularies may not have any associated terms (e.g. https://www.sciencebase.gov/vocab/vocabulary/58d4255ee4b0f974afcf03cb/terms?format=json)
  - Some vocabularies may have descriptions and labels (e.g. https://www.sciencebase.gov/vocab/6112869df0d1326bc2b4bedc/terms?format=json)
    - ScienceBase developer reference: https://my.usgs.gov/confluence/display/sciencebase/ScienceBase
    - ScienceBase vocabulary help: https://www.sciencebase.gov/about/content/sciencebase-vocabulary-user-help

See also: #450

### LINKED ISSUE #550: Allow loading of multiple profiles via a user specified configuration file
## Issue Description:

Profiles are currently hardcoded in a NodeJS module (mdProfiles repository) or custom profiles can be individually configured via the mdEditor profile settings interface. This change would allow the user to specify a profile manifest file listing multiple profiles that would be added to the editor as a set. The manifest file would define the set of profiles to load and specify the locations of their respective configuration files.

Initially, the default manifest file will be located in the mdProfiles repository. Individual profile configuration files will be made available using [jsDelivr](https://www.jsdelivr.com/).

### Expected behavior
  - The user would specify the location of a profile manifest file (default in [mdProfiles repository](https://github.com/adiwg/mdProfiles))
  - Manifest file contains locations of one or more profile definition files and associated schemas
  - Profiles listed in manifest file are displayed in the Profile picklist on the mdEditor primary menu bar and function as expected.

### LINKED ISSUE #566: Specify custom vocabularies in profiles
## Issue Description:

Profiles will allow vocabularies to be defined and loaded when that profile is selected. A profile configuration file should allow one or more custom vocabularies to be defined and load those vocabularies into the editor when the profile is selected.

### Expected behavior

  - A profile definition file would allow specifying one or more custom vocabularies to be associated with a profile.
  - Selecting a profile would add the custom vocabularies to the mdEditor "Pick a thesaurus" list.
  - Switching profiles would update the "Pick a thesaurus" list to include vocabularies associated with the newly selected profile and remove vocabularies associates with any previously selected profiles. (do we want keep default vocabularies associated with the  custom profiles or allow their deletion?)
  - Selecting a custom vocabulary from the picklist, adds a thesaurus card and allows selection of terms as expected.
  - Any vocabularies that have terms selected will always be displayed.

### Dependencies

  - Profile definition files would require a new section for defining the vocabularies associated with that profile.
  - The profile schema ([profile-schema.json](https://github.com/adiwg/mdProfiles/blob/dev/resources/profile-schema.json)) would need to be updated to account for addition of the the above vocabulary section.
  - #550 
  - #546

### PR DESCRIPTION
**Pull request by jwaspin**
### Closing issues

  - closes #61 ([adiwg/mdEditor/issues/61](https://github.com/adiwg/mdEditor/issues/61))
  - closes #459 ([adiwg/mdEditor/issues/459](https://github.com/adiwg/mdEditor/issues/459))
  - closes #460 ([adiwg/mdEditor/issues/460](https://github.com/adiwg/mdEditor/issues/460))
  - closes #482 ([adiwg/mdEditor/issues/482](https://github.com/adiwg/mdEditor/issues/482))
  - closes #550 ([adiwg/mdEditor/issues/550](https://github.com/adiwg/mdEditor/issues/550))
  - closes #566 ([adiwg/mdEditor/issues/566](https://github.com/adiwg/mdEditor/issues/566))

## Pull Request

* **Please check if the PR fulfills these requirements**
  - [x] The commit message follows our guidelines
  - [ ] Tests for the changes have been added (for bug fixes / features)
  - [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
New feature:

mdProfiles dependency removed.

* **What is the current behavior?** (You can also link to an open issue here)
Profiles are packaged as npm module and mdProfiles is configured as a dependency.
These profiles are loaded by the profile service directly from the npm package.

* **What is the new behavior (if this is a feature change)?**
Profiles are loaded at runtime, downloaded from GitHub via JSDelivr,
starting with profiles-list.json, then loading each profile individually.
They are still loaded into the profile service and the pre-existing profiles
have not been modified in any way.

Additionally, when viewing the keywords for a record, the list of vocabularies will
be filtered based on the vocabularies list in the profile configuration
(this is a new addition to the profile configuration in mdProfiles).

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No, it should not break anything.

* **Other information**:
There is a PR for mdProfiles that MUST be merged before this PR
(adiwg/mdProfiles/#32)

This feature increases the dependency on the mdKeywords repository and creates a new dependency on the mdProfiles repository. In mdKeywords, it expects the vocabularies.json file to include all the vocabularies listed in the profiles. In mdProfiles, it expects to find profiles-list.json and all the profiles listed in that file at the location specified. (note, these repositories were previously npm dependencies, they are now runtime dependencies, changing how mdEditor accesses their contents).

### CODE REVIEW

**Comment by jwaspin** [comment]
Does this also close #459?
https://github.com/adiwg/mdEditor/issues/459

**Comment by dwalt** [comment]
See issue #565 before merging.

**Comment by hmaier-fws** [comment]
> Does this also close #459? [adiwg/mdEditor/issues/459](https://github.com/adiwg/mdEditor/issues/459)
> 
> and #460?
> 
> The list in #450 should also be reviewed for overlapping issues. #450 itself would not necessarily be closed by this PR, but maybe?

@jwaspin I've updated the list of issues that this PR would close. Not all items in #450 are addressed by this PR so that one needs to remain open.

**Comment by jwaspin** [comment]
This can be tested at [http://34.201.136.147:8003](http://34.201.136.147:8003)

**Comment by hmaier-fws** [comment]
There seem to be a few issues with this pr

# 1) Selecting "Settings" results in unstable behavior (Chrome)

## Steps
  1. Load editor
  2. Select "Settings" after load is complete

## Observed
  - Browser displays information message `Profile "null" not found. Using default profile.`
  - Browser throws console errors and exhibits intermittent erratic behavior when attempting to edit records.

>>>> [Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
>>>>
>>>> vendor-0068b10387f1d19fea55f4c0e958d868.js:1480 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

# 2) Several vocabularies have non-descriptive names

Several of the vocabularies loaded by the custom profile have non-descriptive names (e.g., category, type, userGroup). I assume this is a remnant of testing and not directly related to this PR. I have created a issue related to this on the mdKeywords repo (adiwg/mdkeywords#7)

It would probably be a good practice for all listed vocabularies to contain a hint icon "?", even if the default is "no description" or something similar. I'll add a new issue for this.

# 3) Thesaurus name not displayed if no keywords selected

## Steps

  - Go to a record and edit keywords
  - Use the "Basic" profile
  - Click "Add Thesaurus", select "GCMD Instruments" from the "Pick a thesaurus" list
  - Repeat the above step for the "ISO Topic Category" and "LCC Deliverable Types"
  - Do not select a keywords. Save changes
  - Navigate to another record. Reload page
  - Return to above record and edit keywords

## Observed

  - Thesaurus # 0 (GCMD) and # 2 (LCC) display the default "Pick a thesaurus" text in the pick list
  - Thesaurus # 1 (ISO) displays "ISO Topic Category" **as would be expected**
  - Attempting to select "GCMD Instruments" from the Thesaurus #0 picklist does not function as expected:
    - The pick list field does not display the selected item name, but selecting another item from the list functions as expected
  -  Thesaurus # 2 exhibits same behavior as above
  - Thesaurus # 1 does not exhibit the above behavior and functions as expected
  - Selecting a keyword during the current edit session results in the vocabulary name being displayed
  - If the recordset is exported before a keyword is selected and then imported into a new edit session, the thesaurus name can no longer be changed, although keywords can be selected from the correct thesaurus 

## Expected behavior:
  - **Current behavior** of the the mdEditor is to retain and display the names of selected thesauri, **even if keywords have not been selected**. This behavior should be identical when working in an active editing session or if importing a recordset into a new editing session.

**Comment by jwaspin** [comment]
@hmaier-fws 1 & 3 I can reproduce, so I'm on those, 2 highlights a bigger discussion point related to the dynamically generated vocabularies.json file and how that is produced. I have made it more robust but there's still more discussion and work to be done to make sure the constructed citations are correct.

On a separate note, and something else that I am aware of in this PR, is profile switching. It won't do anything at all right now, but because the dropdown list is filtered based on the profile, any vocabularies added to a record that are not part of the newly selected profile - the names of those profiles will not be displayed in the same way as happens with issue 3 above. I need some guidance on desired behavior before I can resolve that.

**Comment by jwaspin** [comment]
@hmaier-fws 1 & 3 have been fixed and I see the issue for 2, so I think this is ready for review again.

http://34.201.136.147:8003

**Review by hmaier-fws — APPROVED** [review]
It looks like the issues have been resolved. There are several other items that need to be addressed regarding the profiles. But it looks like things are generally working and we can deal with them after this PR gets merged.

**Pull request merged**
