### PR TITLE
Enhancement 98/coverage description

### PR DESCRIPTION
**Pull request by dvonanderson**
In this, coverage description enhancement #98 we will add the mdJson schema for "coverage description".  Alternatively, we decided to re-name the schema in the app "raster description", but it still shares the coverage description name for the ISO 19115-2 translation. The array of raster description objects will be under the spatial section of the metadata record that is being edited.   @adiwg/mdeditor-reviewers I have created a dev page in which you can play around with the new features at [coverage description dev environment](https://dvonanderson.github.io/mdEditor/). @adiwg/mdeditor-reviewers the steps in recreating the new raster description enhancement are below.

1.  Click on the edit feature for any record that you have loaded, and click on the spatial tab.
2.  Click on "add raster description" in either the main view for spatial or the sub-bar menu to the right.
3.  A raster object will be created and you can now start to edit the name and the description on the same page, or you can click more and it will transition you to the raster route for more editing options.
  * CRUD operations are available on both raster views, which will give you the control to create, read, update and delete.
4. Click on the "more" button for any of the raster objects that have been created, and you now have access to more definitions of need.
  * Raster name(coverageName) and raster description(coverageDescription) are both required fields.
5. Click on "add attribute group" to add an attribute group or an array of attribute groups.
  *  Attribute content type is the only required field for any attribute group.
6. If you have attributes that detail the attribute group, click on "add attribute", and it will take you to the final route in the coverage description schema.
  * None of the fields in the attribute object are required.

### Objectives in enhancement-98/coverage-description
- [x] Create a more condensed user-flow that will allow the users fewer routes to transition from and to, but give the user access to all ISO standards if needed.
- [x]  Create routes for the schema.
- [x] Create nested components for raster
- [x]  Wire up true-false values for "image description" in the raster route.
- [x] Complete all test
- [x] YuiDoc updated

### CODE REVIEW

**Comment by jlblcc** [comment]
Comments from stakeholder call:

- [ ] Rename "Attribute Group"? Suggestion was "Property". Will ask SME reviewers to comment on this before changing.

**Comment by hmaier-fws** [comment]
@dvonanderson can you take a look at the merge conflicts so this can be incorporated into develop?

**Comment by dvonanderson** [comment]
> @dvonanderson can you take a look at the merge conflicts so this can be incorporated into develop?

This has already been merged into the `develop` branch.  I messed around with this thing for two days and forgot we changed the name to `raster description` , but it is broken so I am working on getting it fixed.  Going to close this out.

**Comment by hmaier-fws** [comment]
Resolved by PR #506

**Pull request closed without merging**
