### PR TITLE
584 dynamic load custom profiles from query param url

### LINKED ISSUE #584: Load Custom Profiles from URL
# Loading Dynamic Profiles 

The current dynamic profile loading process includes the NGGDPP profiles by default. This is not desirable so we want to decouple those profiles from the core profiles. 

Using an input box on the profiles' settings page, we can load a secondary set of profiles dynamically, which would allow for the use of anyone's custom profiles, so long as they are formatted as a proper `manifest.json` file.

Custom profiles loaded from the URL should be stored the same way other custom profiles are stored - noting that this is separate from how the core profiles are loaded.

Checklist:

- [x] mdProfiles ready
- [x] mdKeywords ready
- [x] environment variables updated to mdProfiles/mdKeywords master branches
  - [x] keywordsBaseUrl
  - [x] profilesBaseUrl
- [x] loading profiles from query parameter in url
- [x] profiles saved into persistent storage - same method as custom profiles are currently handled
- [x] prevent duplicates
- [x] Load custom thesauri from custom profiles
- [x] Thesaurus issue (# 1 below)
- [x] Hash URL issue (# 2 below)

## Profile manifest file

A **profile manifest file** is a JSON file containing an array of one or more references to mdEditor profile definitions.  The format is as follows:

```
[
  {
    "name": "definition name",
    "url": "url to profile definition"
  }
]
```

### Example manifest file
```
[
  {
    "name": "AK Region Project Profile",
    "url": "https://usfws.github.io/ak-md-profiles/ak-proj-profile.json"
  },
  {
    "name": "AK Region Product Profile",
    "url": "https://usfws.github.io/ak-md-profiles/ak-proj-profile.json"
  }
]
```

### PR DESCRIPTION
**Pull request by jwaspin**
Closes
#584 

### Testing
http://23.23.4.125:8002/ [DOWN FOR MAINTENANCE]

#### Query Parameter Usage
[http://23.23.4.125:8002/dashboard?loadProfilesFrom=https://raw.githubusercontent.com/USGS-NGGDPP/mdEditor-profiles/main/manifest.json](http://23.23.4.125:8002/dashboard?loadProfilesFrom=https://raw.githubusercontent.com/USGS-NGGDPP/mdEditor-profiles/main/manifest.json)
OR for hashed URLs
[http://23.23.4.125:8002/#/dashboard?loadProfilesFrom=https://raw.githubusercontent.com/USGS-NGGDPP/mdEditor-profiles/main/manifest.json](http://23.23.4.125:8002/#/dashboard?loadProfilesFrom=https://raw.githubusercontent.com/USGS-NGGDPP/mdEditor-profiles/main/manifest.json)

# Changes

**Increase minor version number**

* Remove NGGDPP profiles from core profiles
* New feature: load profiles using query parameter
* Refactored
  * environment variables for manifest file urls
  * keyword service
  * profile service
  * custom-profile model & service
  * thesaurus route & dropdown menu component

## Breaking Changes

By removing the functionality to automatically load NGGDPP profiles, anyone using those profiles will need to re-load them using the query parameter. The profiles in the NGGDPP repository have a slightly different format because of other changes being made, but if the user re-selects a profile after loading them from the query parameter, that should, in theory, fix the record. This should also be a limited impact because the profiles have not existed as core profiles for very long.

### CODE REVIEW

**Comment by hmaier-fws** [comment]
@jwaspin I'm going to change this PR to draft pending the thesaurus issue described in #584

**Comment by jwaspin** [comment]
@hmaier-fws Fixed the bugs and redeployed the test container on :8002 so that's good to go for testing.

**Comment by hmaier-fws** [comment]
@jwaspin There is a problem reading the name and description of existing custom profiles.

Steps to recreate:
  1. import existing custom profiles via "Import mdJSON from Online URL" using this example file: https://raw.githubusercontent.com/hmaier-fws/ak-md-profiles/dev/ak-profile-pkg-test-20231218.json
  2. Select "Preview JSON" for a custom profile and note that a "title" and "description" are present.
  3. Create a new metadata record.
  4. Change profile from "Full".
  5. The Profile picklist displays three blank entries.
  6. The "Manage Profiles" screen does not display the titles.
  7. Selecting a profile's "Edit" button shows that neither a title nor description are present.

The title and definitions should be obtained from the mdEditor JSON object of type `"type": "custom-profiles"`. The current information seems to be coming from the "**profile definition**" file (mdEditor JSON object `"type": "profiles"`).

A Custom profile is a combination of a profile definition and schema. If a schema is not provided (as in the case of the test query parameter) then the default schema is applied. A **single profile definition** can be used in combination with multiple schemas, resulting in multiple **custom profiles**.

**Comment by jwaspin** [comment]
@hmaier-fws I went all the way back to v0.11.0-dev.2 and found that this issue has existed for a while and is not being introduced by this commit.

**Comment by jwaspin** [comment]
@hmaier-fws I'm closing this PR because the PR from branch feature/load-profiles-from-url is replacing it and the feature is no longer loading from a query parameter, I added an input box and a button instead.

Importantly, I did more than just fix the issue you mentioned here, the bug was deeper so I fixed it completely.

**Comment by jwaspin** [comment]
Replaced by #697

**Pull request closed without merging**
